language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
sudo: false
install:
- pip install -U pip setuptools wheel
- pip install .[testing,linting]
before_script:
- python -m tests.test_server &
script:
- flake8 .
- bandit -r requests_ntlm3
- py.test --ignore=tests/functional/test_functional.py --ignore=tests/test_server.py tests
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: __token__
  # on:
  #   tags: true
  skip_existing: true
  password:
    secure: AXt89NUoJXjS5eWDabmvHU2GQm0pMxK0SaTPnpgvIVfyDCnD3SImSaT3tEACLoOfJlnTs1AkZGjbfirdTi1R/mNzhdez6UKMWl++hz9RNTza+B3g/CnrdoyLh/hp7GLtNwjy4NF6sZwhFxMwkw9DHPXi7UWuBLy1Gy/47OW+Z7sEHjH84ChCneQVWO68cACdRryfaFoQwuDgVVpbiKfZYG964+dirAwuaCv0eKarcDfYD6v6myUk/WMQ7Eu/oNZUcLnA0JtMnbu2wzzHGXMBxRsgL2aGij1VMstZmqR9CYcgTM0/b7K7Z0G+Tn5ztaztp9ov1piN4+9ZAeRJ/iM4i0o/09bMsPt1d0aHH00pVxupBODazx/GlsiJMJwTctoY17Ozf5JEGsAA3jMGj4N3A27zunFgGroWVceqzB5dsVGAAO1fYUQDiaGy/M8INhLaizuN873zjkOGF2YxsA/BTLcPnQtCTyxxxieP6OqaH/9aphgwLUQBHNaEkCZgfd6+ORHWQvybkH7hB9O8Mosx4FcX/nlhSJx+0RnDcNCCTMlTP2F4edzeZuuY8V0FWp6IAuKuMVqNTYUXL6Rvw0XciuI5E6bizG33ySRTMznpedKTA/54hGnW6i5TEC0vsO294r03yeObSPK0TXLLqKnbjDQwJP+xg8Y8/97X7zz9OgM=
